import React from 'react';
import { Button } from './SharedComponents';

interface PrivacyPolicyViewProps {
  onBack: () => void;
  onClearAllLocalData: () => void;
  darkMode: boolean;
  highContrast: boolean;
}

export const PrivacyPolicyView: React.FC<PrivacyPolicyViewProps> = ({
  onBack,
  onClearAllLocalData,
  darkMode,
  highContrast
}) => {
  return (
    <div className={`h-full flex flex-col max-w-4xl mx-auto ${highContrast ? 'text-yellow-300' : darkMode ? 'text-white' : 'text-slate-800'}`}>
      {/* Header */}
      <div className={`flex items-center gap-3 pb-4 mb-4 border-b ${darkMode ? 'border-slate-800' : 'border-slate-200'}`}>
        <button
          onClick={onBack}
          className={`p-2 rounded-lg transition-colors ${darkMode ? 'hover:bg-slate-800 text-slate-300' : 'hover:bg-slate-100 text-slate-600'}`}
          title="Back to Dashboard"
        >
          <i className="fas fa-arrow-left text-lg"></i>
        </button>
        <div>
          <h2 className="text-xl font-bold">Privacy, Transparency & Medical Disclaimer</h2>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            How your health data is handled, protected, and governed in MediMind AI
          </p>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto space-y-6 pr-1 pb-8 text-xs sm:text-sm">
        {/* 1. Core Medical Disclaimer */}
        <div className={`p-4 rounded-2xl border ${
          darkMode ? 'bg-amber-950/20 border-amber-800/60 text-amber-200' : 'bg-amber-50 border-amber-200 text-amber-900'
        }`}>
          <div className="flex items-center gap-2 mb-2 font-bold text-sm text-amber-800 dark:text-amber-300">
            <i className="fas fa-shield-alt text-base"></i>
            <h3>Medical Disclaimer (Non-Diagnostic)</h3>
          </div>
          <p className="leading-relaxed mb-2">
            MediMind AI is an educational second-opinion and document comprehension tool. It does <strong>not</strong> provide medical diagnoses, clinical treatment plans, or definitive medical opinions. The information generated by AI models may not account for your complete medical history or unique physical condition.
          </p>
          <p className="leading-relaxed">
            <strong>Emergency Care:</strong> If you are experiencing sudden severe symptoms—including chest pain, difficulty breathing, slurred speech, acute allergic reactions, or uncontrollable bleeding—do not wait for AI responses. Contact emergency services (911, 112, or your local emergency hotline) immediately.
          </p>
        </div>

        {/* 2. Privacy & Data Handling */}
        <div className={`p-4 rounded-2xl border ${
          darkMode ? 'bg-slate-800/60 border-slate-700' : 'bg-white border-slate-200'
        }`}>
          <h3 className="text-sm font-bold mb-3 flex items-center gap-2">
            <i className="fas fa-user-lock text-blue-500"></i>
            How Your Data is Processed
          </h3>
          <div className="space-y-3 text-slate-600 dark:text-slate-300 leading-relaxed">
            <p>
              <strong>1. Ephemeral Server Processing:</strong> When you upload a medical report or submit a symptom query, the document is sent over encrypted TLS to our secure backend API. The data is parsed in-memory, analyzed by the AI model, and the structured response is returned. Uploaded files are not permanently stored on third-party servers.
            </p>
            <p>
              <strong>2. Client-Side Sovereignty:</strong> Your medical reports, medications, blood pressure entries, and health history are stored locally in your browser’s isolated storage sandbox by default.
            </p>
            <p>
              <strong>3. No Ad Tracking or Profiling:</strong> MediMind AI does not sell, broker, or monetize your health data, nor do we run commercial advertising trackers.
            </p>
            <p>
              <strong>4. API Key Security:</strong> All AI interactions route through an enterprise server-side proxy. Private API keys and credentials are never transmitted to or inspectable within your browser.
            </p>
          </div>
        </div>

        {/* 3. User Data Rights & 1-Click Wipe */}
        <div className={`p-4 rounded-2xl border ${
          darkMode ? 'bg-red-950/20 border-red-900/60' : 'bg-red-50/50 border-red-200'
        }`}>
          <h3 className="text-sm font-bold text-red-700 dark:text-red-400 mb-2 flex items-center gap-2">
            <i className="fas fa-trash-alt"></i>
            Your Data Rights & Erasure Controls
          </h3>
          <p className="text-slate-600 dark:text-slate-300 mb-4 leading-relaxed">
            You maintain complete control over your health records. You can delete individual reports, clear medication alarms, or perform a complete wipe of all locally saved data at any time.
          </p>

          <button
            onClick={() => {
              if (confirm('Are you sure you want to completely erase all local reports, medication alarms, chat history, and vitals? This action cannot be reversed.')) {
                onClearAllLocalData();
                alert('All local MediMind AI data has been wiped.');
              }
            }}
            className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold text-xs shadow-sm transition-colors"
          >
            <i className="fas fa-trash mr-1.5"></i> Permanently Wipe All Local Data
          </button>
        </div>

        {/* 4. Trusted Grounding & Citations */}
        <div className={`p-4 rounded-2xl border ${
          darkMode ? 'bg-slate-800/60 border-slate-700' : 'bg-white border-slate-200'
        }`}>
          <h3 className="text-sm font-bold mb-2 flex items-center gap-2">
            <i className="fas fa-book-medical text-emerald-500"></i>
            Trusted Source Grounding (RAG)
          </h3>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
            To combat medical hallucinations, MediMind queries an authoritative medical reference layer drawn from verified clinical institutions including the <strong>World Health Organization (WHO)</strong>, <strong>Centers for Disease Control and Prevention (CDC)</strong>, <strong>MedlinePlus / NIH</strong>, and the <strong>American Heart Association</strong>. Citations with direct links and access dates are provided for patient transparency.
          </p>
        </div>
      </div>
    </div>
  );
};
